// <auto-generated />
namespace FinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_fks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_fks));
        
        string IMigrationMetadata.Id
        {
            get { return "201704181647495_new_fks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
